# -*- mode: ruby -*-
# vi: set ft=ruby :

# NAME: Vagrantfile
# AUTHOR: Joaquin Menchaca
# CREATED: 2015-11-23
#
# PURPOSE: Configuration Script evalued by Vagrant.  Does the following:
#  * Configures three systems: chefserver, work, node
#  * Configures private network with static IP addresses
#  * Provisions systems using shell scripts
# DEPENDENCIES:
#  * Vagrant 1.7.4+, VirtualBox 4.3.x or VirtualBox 5.x
#  * Global Configuration - global.json
# NOTES:
#  * VirtualBox systems will need to have GuestEditions installed so that
#    `/vagrant` will be mounted in the guest operating system
#  * Vagrant 1.8.5 is not compatible with CentOS (RHEL) 7 systems
#    https://github.com/mitchellh/vagrant/issues/5186

CONFIGFILE_HOSTS=ENV['VAGRANT_CONFIG'] || './config/default.hosts'
TIME = Time.now.strftime("%Y%m%d%H%M%S")
PRIMARY_SYSTEM = "workstation" # designate default primary system

@hosts = Hash.new  # create hash to configure systems
# Read Default Hosts File:  'ipaddress hostname'
File.readlines(CONFIGFILE_HOSTS).map(&:chomp).each do |line|
  ipaddr, hostname = line.split(/\s+/)
  @hosts[hostname] = ipaddr
end

Vagrant.configure("2") do |config|
  @hosts.each do |hostname, ipaddr|
    default = if hostname == PRIMARY_SYSTEM then true else false end
    config.vm.define hostname, primary: default  do |host|
      host.vm.box = "geerlingguy/centos7"
      host.vm.hostname = "#{hostname}"
      host.vm.network "private_network", ip: ipaddr
      case hostname
      when /chefserver/
          host.vm.provider "virtualbox" do |vbox|
            vbox.memory = 4096
            vbox.cpus = 2
            vbox.name = "centos_7_#{hostname}_#{TIME}"
          end
      else
          host.vm.provider("virtualbox") { |vbox| vbox.name = "centos_7_#{hostname}_#{TIME}" }
      end

      host.vm.synced_folder ".", "/vagrant", disabled: false

      # Provision Systems with Shell Scripts
      host.vm.provision "shell", path: "scripts/#{hostname}.sh"
     end
  end
end
