# -*- mode: ruby -*-
# vi: set ft=ruby :

# NAME: Vagrantfile
# AUTHOR: Joaquin Menchaca
# CREATED: 2015-11-23
#
# PURPOSE: Configuration Script evalued by Vagrant.  Does the following:
#  * Configures three systems: chefserver, work, node
#  * Configures private network with static IP addresses
#  * Provions systems using shell scripts
# DEPENDENCIES:
#  * Vagrant 1.7.4+, VirtualBox 4.3.x or VirtualBox 5.x
#  * Global Configuration - global.json
# NOTES:
#  * VirtualBox systems will need to have GuestEditions installed so that
#  *  `/vagrant` will be mounted in the guest operating system

time = Time.now.strftime("%Y%m%d%H%M%S")

begin
   file = open(".config/global.json")
 rescue StandardError=>e
   puts "Error: #{e}"
 else
   json = file.read
   ipaddr = JSON.parse(json)['ipaddr']
end

Vagrant.configure("2") do |config|
  # CHEF SERVER
  config.vm.define "chefserver" do |chefserver|
    chefserver.vm.box = "geerlingguy/centos7"
    chefserver.vm.hostname = "chefserver"
    chefserver.vm.network "private_network", ip: "#{ipaddr['chefserver']}"

    chefserver.vm.provider "virtualbox" do |vbox|
      vbox.memory = 4096
      vbox.cpus = 2
      vbox.name = "chefserver_centos7_#{time}"
    end

    chefserver.vm.provision "shell", path: "setup-all.sh"     # ssh convenience
    chefserver.vm.provision "shell", path: "setup-chefserver.sh" # install ChefDK
    # Configure Initial Setup, Admin Account, and Organization
    chefserver.vm.provision "shell", path: "config-chefserver.sh"
  end

  # WORKSTATION
  config.vm.define "work", primary: true do |work|
    work.vm.box = "geerlingguy/centos7"
    work.vm.hostname = "work"
    work.vm.network "private_network", ip: "#{ipaddr['work']}"

    work.vm.provider("virtualbox") { |vbox| vbox.name = "work_centos7_#{time}" }

    work.vm.provision "shell", path: "setup-all.sh"    # ssh convenience
    work.vm.provision "shell", path: "setup-work.sh"   # packages
    work.vm.provision "shell", path: "setup-chefdk.sh" # install ChefDK
    # Configure Workstation to Use Chef Server
    work.vm.provision "shell", path: "config-workstation.sh"
  end

  # NODE TO CONFIGURE
  config.vm.define "node" do |node|
    node.vm.box = "geerlingguy/centos7"
    node.vm.hostname = "node"
    node.vm.network "private_network", ip: "#{ipaddr['node']}"

    node.vm.provider("virtualbox") { |vbox| vbox.name = "node_centos7_#{time}" }

    node.vm.provision "shell", path: "setup-all.sh"     # ssh convenience
  end
end
